kind: KwokctlConfiguration
apiVersion: config.kwok.x-k8s.io/v1alpha1
options:
  prometheusPort: 9090
componentsPatches:
  - name: kwok-controller
    extraEnvs:
      - name: "GOMAXPROCS"
        value: "96"
  - name: etcd
    extraEnvs:
      - name: "GOMAXPROCS"
        value: "96"
  - name: kube-apiserver
    extraArgs:
    - key: runtime-config
      value: "resource.k8s.io/v1beta1=true"
    - key: max-requests-inflight
      value: "10000"
    - key: max-mutating-requests-inflight
      value: "5000"
    extraEnvs:
      - name: "GOMAXPROCS"
        value: "96"
  - name: kube-scheduler
    extraArgs:
      - key: leader-elect
        value: "false"
    extraEnvs:
      - name: "GOMAXPROCS"
        value: "96"
  - name: kube-controller-manager
    extraArgs:
      - key: leader-elect
        value: "false"
      - key: concurrent-job-syncs
        value: "700"
      - key: terminated-pod-gc-threshold
        value: "150000"
      - key: kube-api-qps
        value: "2000"
      - key: kube-api-burst
        value: "4000"
    extraEnvs:
      - name: "GOMAXPROCS"
        value: "96"