apiVersion: resource.k8s.io/v1beta1
kind: ResourceSlice
metadata:
  name: ${resource_slice_name}
spec:
  devices:
  - basic:
      attributes:
        architecture:
          string: Ada Lovelace
        brand:
          string: Kwok
        cudaComputeCapability:
          version: 8.9.0
        cudaDriverVersion:
          version: 12.9.0
        driverVersion:
          version: 575.57.8
        index:
          int: 0
        minor:
          int: 0
        productName:
          string: Kwok L4
        type:
          string: gpu
      capacity:
        memory:
          value: 23034Mi
    name: gpu-0
  driver: gpu.nvidia.com
  nodeName: ${node_name}
  pool:
    name: ${node_name}
    resourceSliceCount: 1