apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-head
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-head
  template:
    metadata:
      labels:
        app: mock-head
    spec:
      nodeName: kwok-kwok-control-plane
      containers:
      - name: server
        image: docker.io/library/python:3.11-alpine
        ports:
        - containerPort: 8265
        volumeMounts:
        - name: mock-head
          mountPath: /app
        command: ["python"]
        args: ["/app/server.py"]
      volumes:
      - name: mock-head
        configMap:
          name: mock-head