apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderMultusConfig
metadata:
  name: ipvlan-eth0
  namespace: spiderpool
spec:
  cniType: ipvlan
  enableCoordinator: true
  ipvlan:
    master:
    - eth0