apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: kwok-cluster-queue
spec:
  cohort: kwok-cohort
  flavorFungibility:
    whenCanBorrow: Borrow
    whenCanPreempt: TryNextFlavor
  namespaceSelector: {}
  preemption:
    borrowWithinCohort:
      policy: LowerPriority
    reclaimWithinCohort: Any
    withinClusterQueue: LowerPriority
  queueingStrategy: BestEffortFIFO
  resourceGroups:
  - coveredResources:
    - cpu
    - memory
    flavors:
    - name: kwok-resource-flavor
      resources:
      - borrowingLimit: "390144"
        name: cpu
        nominalQuota: "1000"
      - borrowingLimit: 2568Ti
        name: memory
        nominalQuota: 1Ti
  stopPolicy: None
