apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: kwok-cluster-queue
spec:
  cohort: kwok
  flavorFungibility:
    whenCanBorrow: Borrow
    whenCanPreempt: TryNextFlavor
  namespaceSelector: {}
  preemption:
    borrowWithinCohort:
      policy: LowerPriority
    reclaimWithinCohort: Any
    withinClusterQueue: LowerPriority
  queueingStrategy: BestEffortFIFO
  resourceGroups:
  - coveredResources:
    - cpu
    - memory
    - nvidia.com/gpu
    flavors:
    - name: kwok
      resources:
      - borrowingLimit: "390144"
        name: cpu
        nominalQuota: "0"
      - borrowingLimit: 2568Ti
        name: memory
        nominalQuota: "0"
      - borrowingLimit: "12184"
        name: nvidia.com/gpu
        nominalQuota: "0"
  stopPolicy: None
