apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: gb300-cluster-queue
spec:
  cohort: gb300-cohort
  flavorFungibility:
    whenCanBorrow: Borrow
    whenCanPreempt: TryNextFlavor
  namespaceSelector: {}
  preemption:
    borrowWithinCohort:
      policy: LowerPriority
    reclaimWithinCohort: Any
    withinClusterQueue: LowerPriority
  queueingStrategy: BestEffortFIFO
  resourceGroups:
  - coveredResources:
    - cpu
    - memory
    - nvidia.com/gpu
    flavors:
    - name: gb300-resource-flavor
      resources:
      - name: cpu
        nominalQuota: "1000"
      - name: memory
        nominalQuota: 1Ti
      - name: nvidia.com/gpu
        nominalQuota: "576"
  stopPolicy: None
