apiVersion: v1
kind: Pod
metadata:
  name: debugger
  labels:
    app: debugger
spec:
  hostNetwork: true
  hostPID: true
  restartPolicy: Never
  tolerations:
    - operator: Exists
  containers:
    - name: toolbox
      image: ubuntu:22.04
      command: ["/bin/bash", "-c"]
      args:
        - >
          mount --rbind /dev /host/dev &&
          mount --rbind /sys /host/sys &&
          mount --rbind /proc /host/proc &&
          chroot /host /bin/bash -c 'sleep infinity'
      securityContext:
        privileged: true
        runAsUser: 0
        runAsGroup: 0
        allowPrivilegeEscalation: true
        capabilities:
          add:
            - SYS_MODULE
            - NET_ADMIN
            - SYS_RAWIO
            - SYS_ADMIN
      volumeMounts:
        - name: host-root
          mountPath: /host
          mountPropagation: Bidirectional
  volumes:
    - name: host-root
      hostPath:
        path: /
        type: Directory

