 resources:
  gpus:
    enabled: false
  computeDomains:
    enabled: true
 controller:
   affinity:
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: kubernetes.azure.com/mode
             operator: In
             values:
             - system
 nvidiaDriverRoot: "/run/nvidia/driver"