apiVersion: batch/v1
kind: Job
metadata:
  name: job
  namespace: default
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: fake-pod
    spec:
      restartPolicy: Never
      containers:
      - name: fake-worker
        image: fake-image
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1