apiVersion: batch/v1
kind: Job
metadata:
  name: <JOB>
  namespace: <NAMESPACE>
spec:
  completions: <REPLICAS>
  parallelism: <REPLICAS>
  template:
    metadata:
      labels:
        app: fake
    spec:
      restartPolicy: Never
      nodeSelector:
        type: kwok
      tolerations:
      - key: "kwok.x-k8s.io/node"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: fake-worker
        image: fake-image
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1