apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: test-2
spec:
  rayVersion: '2.41.0'
  headGroupSpec:
    rayStartParams: {}
    template:
      spec:
        containers:
          - name: ray-head
            image: rayproject/ray:2.41.0
  workerGroupSpecs:
    - replicas: 8
      groupName: gpu
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-worker
              image: rayproject/ray:2.41.0
              resources:
                requests:
                  nvidia.com/gpu: 1
                limits:
                  nvidia.com/gpu: 1