{{- range $i := until (int .Values.nodeCount) }}
---
apiVersion: v1
kind: Node
metadata:
  name: kwok-{{ $i }}
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    kwok.x-k8s.io/node: fake
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: kwok-{{ $i }}
    kubernetes.io/os: linux
    kubernetes.io/role: agent
    node-role.kubernetes.io/agent: ""
    type: kwok
    kwok.x-k8s.io/node: "true"
    nvidia.com/gpu: "true"
spec:
  providerID: kwok://kwok-{{ $i }}
  taints:
  - effect: NoSchedule
    key: kwok.x-k8s.io/node
    value: fake
status:
  allocatable:
    cpu: 96
    memory: 1Ti
    pods: 110
    nvidia.com/gpu: "8"
  capacity:
    cpu: 96
    memory: 1Ti
    pods: 110
    nvidia.com/gpu: "8"
  nodeInfo:
    architecture: amd64
    bootID: ""
    containerRuntimeVersion: ""
    kernelVersion: ""
    kubeProxyVersion: fake
    kubeletVersion: fake
    machineID: ""
    operatingSystem: linux
    osImage: ""
    systemUUID: ""
  phase: Running
{{- end }}
