apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: rdma-net-ipam
spec:
  nodeSelector:
    kubernetes.io/hostname: aks-gpupool-23813202-vmss000001
  restartPolicy: OnFailure
  containers:
  - image: mellanox/cuda-perftest
    name: rdma-gpu-test-ctr
    securityContext:
      capabilities:
        add: [ "IPC_LOCK" ]
    resources:
      limits:
        nvidia.com/gpu: 1
        rdma/rdma_shared_device_a: 1
      requests:
        nvidia.com/gpu: 1
        rdma/rdma_shared_device_a: 1