kind: KwokctlConfiguration
apiVersion: config.kwok.x-k8s.io/v1alpha1
componentsPatches:
  - name: kwok-controller
    extraEnvs:
      - name: "GOMAXPROCS"
        value: "4"
  - name: etcd
    extraEnvs:
      - name: "GOMAXPROCS"
        value: "4"
  - name: kube-apiserver
    extraEnvs:
      - name: "GOMAXPROCS"
        value: "8"
  - name: kube-scheduler
    extraEnvs:
      - name: "GOMAXPROCS"
        value: "8"
  - name: kube-controller-manager
    extraEnvs:
      - name: "GOMAXPROCS"
        value: "8"
    extraArgs:
      - key: "concurrent-namespace-syncs"
        value: "100"
      - key: "concurrent-job-syncs"
        value: "1000"
      - key: "concurrent-deployment-syncs"
        value: "100"
      - key: "concurrent-replicaset-syncs"
        value: "100"
      - key: "concurrent-statefulset-syncs"
        value: "100"
      - key: "concurrent-service-syncs"
        value: "10"
      - key: "concurrent-endpoint-syncs"
        value: "100"