apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderIPPool
metadata:
  name: aks-system-27117018-vms23
spec:
  subnet: 10.224.0.48/28
  ips:
    - 10.224.0.50-10.224.0.62
  gateway: 10.224.0.49
  default: true
  nodeName: ["aks-system-27117018-vms23"]
  multusName: ["kube-system/ipvlan-eth0"]