apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderIPPool
metadata:
  name: aks-user-17598352-vms4
spec:
  subnet: 10.224.0.96/28
  ips:
    - 10.224.0.98-10.224.0.110
  gateway: 10.224.0.97
  default: true
  nodeName: ["aks-user-17598352-vms4"]
  multusName: ["kube-system/ipvlan-eth0"]