apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: gpu-nic-aligned
spec:
  spec:
    devices:
      requests:
      - name: gpu-0
        exactly:
          deviceClassName: gpu.nvidia.com
          count: 4
      - name: nic-0
        exactly:
          deviceClassName: dranet.net
          count: 4
      - name: gpu-1
        exactly:
          deviceClassName: gpu.nvidia.com
          count: 4
      - name: nic-1
        exactly:
          deviceClassName: dranet.net
          count: 4
      constraints:
      - matchAttribute: resource.kubernetes.io/pcieRoot
        requests:
        - gpu-0
        - nic-0
      - matchAttribute: resource.kubernetes.io/pcieRoot
        requests:
        - gpu-1
        - nic-1
