apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  nodeSelector:
    kubernetes.io/hostname: aks-user-19641872-vmss000000
  hostNetwork: true
  containers:
  - name: busybox
    image: busybox:1.32.0
    imagePullPolicy: IfNotPresent
    command: ["sleep", "3600"]
